baseURL = "https://gadgetlunatic.com/"
languageCode = "ja"
title = "gadgetlunatic"
hasCJKLanguage = true
paginate = 3
googleAnalytics = "UA-131471081-1"

pygmentsCodeFences= true
pygmentsUseClasses = true

[menu]
	[[menu.main]]
		identifier = "twitter"
		name = "Twitter"
		url = "https://twitter.com/kazushikonosu"
		weight = 100
	[[menu.main]]
		identifier = "github"
		name = "Github"
		url = "https://github.com/kazushisan"
		weight = 110
