// Generated by ReScript, PLEASE EDIT WITH CARE

var parentElement = e => e.parentElement || undefined;
var previousElementSibling = e => e.previousElementSibling || undefined;
export { parentElement, previousElementSibling };
/* No side effect */