// Generated by ReScript, PLEASE EDIT WITH CARE

import * as UseLazy from './useLazy';
function useLazyPage(prim0, prim1) {
  return UseLazy.useLazyPage(prim0, prim1);
}
function useLazyLatexList(prim) {
  return UseLazy.useLazyLatexList();
}
function useLazyPostList(prim) {
  return UseLazy.useLazyPostList();
}
export { useLazyPage, useLazyLatexList, useLazyPostList };
/* ./useLazy Not a pure module */
