// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_exn from "rescript/lib/es6/js_exn.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_exceptions from "rescript/lib/es6/caml_exceptions.js";

var InvalidDataException = /* @__PURE__ */Caml_exceptions.create("Extract.InvalidDataException");

function extract(param) {
  var path = param.path;
  var data = param.data;
  if (data.title === undefined) {
    Js_exn.raiseError("invalid data for " + path + "");
  }
  if (data.date === undefined) {
    Js_exn.raiseError("invalid data for " + path + "");
  }
  return {
          path: path,
          title: Belt_Option.getWithDefault(data.title, ""),
          date: Belt_Option.getWithDefault(data.date, ""),
          permalink: data.permalink,
          modifiedDate: data.modifiedDate,
          hash: data.hash,
          weight: Belt_Option.getWithDefault(data.weight, 0)
        };
}

export {
  InvalidDataException ,
  extract ,
}
/* No side effect */
