// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Extract from "./Extract.bs.js";

function query(list) {
  return list.map(Extract.extract).filter(function (item) {
                  return item.path.startsWith("/latex");
                }).sort(function (a, b) {
                return a.weight - b.weight | 0;
              }).map(function (param) {
              return {
                      title: param.title,
                      path: param.path,
                      date: param.date,
                      modifiedDate: param.modifiedDate
                    };
            });
}

var $$default = query;

export {
  query ,
  $$default ,
  $$default as default,
}
/* No side effect */
