// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Head from "../components/Head.bs.js";
import * as Icon from "../components/Icon.bs.js";
import * as Lazy from "../hooks/Lazy.bs.js";
import * as Link from "../components/Link.bs.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as PostMeta from "../components/PostMeta.bs.js";
import * as TableOfContents from "../components/TableOfContents.bs.js";

function Latex(props) {
  var path = props.path;
  var match = Lazy.useLazyPage(path, props.load);
  var title = match.title;
  var pages = Lazy.useLazyLatexList(undefined);
  var match$1 = React.useState(function () {
        return false;
      });
  var setShow = match$1[1];
  return React.createElement("div", {
              className: "xl:flex xl:justify-center"
            }, React.createElement(Head.make, {
                  title: "LaTeXのガイド " + title + " | gadgetlunatic",
                  path: path
                }), React.createElement("div", undefined, React.createElement("div", {
                      className: "container md:mx-auto max-w-4xl xl:hidden"
                    }, React.createElement("div", {
                          className: "p-4 flex justify-between"
                        }, React.createElement("div", {
                              className: "text-slate-700 font-bold"
                            }, React.createElement("span", undefined, "LaTeXのガイド"), React.createElement("span", {
                                  className: "before:content-['/'] before:text-slate-300 before:m-1"
                                }, title)), React.createElement("button", {
                              onClick: (function (param) {
                                  Curry._1(setShow, (function (value) {
                                          return !value;
                                        }));
                                })
                            }, React.createElement(Icon.Bar3.make, {
                                  className: "w-6"
                                })))), match$1[0] ? React.createElement("div", {
                        className: "fixed inset-0 flex-col flex z-10 xl:hidden"
                      }, React.createElement("nav", {
                            className: " bg-white shadow overflow-y-scroll m-4 rounded-md flex-initial md:mx-auto md:m-4 md:w-[calc(100%-2rem)] max-w-4xl"
                          }, React.createElement("div", {
                                className: "flex justify-between p-4"
                              }, React.createElement("div", {
                                    className: "text-slate-700 font-bold"
                                  }, "LaTeXのガイド"), React.createElement("button", {
                                    onClick: (function (param) {
                                        Curry._1(setShow, (function (value) {
                                                return !value;
                                              }));
                                      })
                                  }, React.createElement(Icon.XMark.make, {
                                        className: "w-6"
                                      }))), React.createElement("div", {
                                className: "mx-4 pb-2 border-slate-100 border-t"
                              }, pages.map(function (page) {
                                    return React.createElement("div", {
                                                key: page.path,
                                                className: "" + (
                                                  path === page.path ? "text-blue-500" : "text-slate-700"
                                                ) + " my-4"
                                              }, React.createElement(Link.make, {
                                                    children: page.title,
                                                    to: page.path,
                                                    onClick: (function (param) {
                                                        Curry._1(setShow, (function (param) {
                                                                return false;
                                                              }));
                                                      })
                                                  }));
                                  })))) : null), React.createElement("div", {
                  className: "container md:mx-auto xl:mx-0 max-w-4xl box-content flex-none"
                }, React.createElement("div", {
                      className: "px-4"
                    }, React.createElement("header", undefined, React.createElement("h1", {
                              className: "font-bold text-3xl my-8"
                            }, title), React.createElement("div", {
                              className: "my-8"
                            }, React.createElement(PostMeta.make, {
                                  date: match.date,
                                  permalink: match.permalink,
                                  modifiedDate: match.modifiedDate,
                                  hash: match.hash
                                }))), React.createElement("article", {
                          className: "prose mb-16 max-w-none prose-slate"
                        }, match.element))), React.createElement("div", {
                  className: "hidden xl:block flex-none w-72"
                }, React.createElement("div", {
                      className: "p-4 sticky mt-4 top-4"
                    }, React.createElement("nav", {
                          className: "mb-8 pb-8 border-b border-slate-100"
                        }, React.createElement("div", {
                              className: "font-bold"
                            }, "LaTeXのガイド"), pages.map(function (page) {
                              return React.createElement("div", {
                                          key: page.path,
                                          className: "" + (
                                            path === page.path ? "text-blue-500" : "text-slate-700"
                                          ) + " my-2"
                                        }, React.createElement(Link.make, {
                                              children: page.title,
                                              to: page.path,
                                              onClick: (function (param) {
                                                  Curry._1(setShow, (function (param) {
                                                          return false;
                                                        }));
                                                })
                                            }));
                            })), React.createElement(TableOfContents.make, {
                          headings: match.headings
                        }))));
}

var make = Latex;

export {
  make ,
}
/* Head Not a pure module */
