// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

var year = new Date().getFullYear().toString();

function Footer(props) {
  return React.createElement("footer", undefined, React.createElement("div", {
                  className: "container md:mx-auto max-w-4xl box-content py-16 " + (
                    props.isArticle ? "xl:pr-72" : ""
                  ) + ""
                }, React.createElement("div", {
                      className: "p-4"
                    }, React.createElement("div", undefined, React.createElement("h3", {
                              className: "font-bold text-lg"
                            }, "gadgetlunatic"), React.createElement("p", undefined, React.createElement("a", {
                                  href: "https://github.com/kazushisan/gadgetlunatic"
                                }, "github.com/kazushisan/gadgetlunatic"))), React.createElement("div", {
                          className: "mt-4"
                        }, React.createElement("p", undefined, "© " + year + " ", React.createElement("a", {
                                  className: "text-blue-500 hover:text-blue",
                                  href: "https://twitter.com/kazushikonosu"
                                }, "@kazushikonosu"))))));
}

var make = Footer;

export {
  year ,
  make ,
}
/* year Not a pure module */
