// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactHelmetAsync from "react-helmet-async";
function Head(props) {
  return <ReactHelmetAsync.Helmet children={null}><title>{props.title}</title><link href={"https://gadgetlunatic.com" + props.path + ""} rel="canonical" /></ReactHelmetAsync.Helmet>;
}
var make = Head;
export { make };
/* react Not a pure module */