// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Link from "./Link.bs.js";
import * as React from "react";

function Header(props) {
  return React.createElement("header", undefined, React.createElement("div", {
                  className: "container md:mx-auto max-w-4xl box-content " + (
                    props.isArticle ? "xl:pr-72" : ""
                  ) + ""
                }, React.createElement("div", {
                      className: "p-4 flex justify-start items-center"
                    }, React.createElement(Link.make, {
                          children: React.createElement("h1", {
                                className: "font-bold text-lg"
                              }, "gadgetlunatic"),
                          to: "/"
                        }), React.createElement(Link.make, {
                          children: "ブログ",
                          to: "/",
                          className: "text-slate-700 ml-4 text-sm"
                        }), React.createElement("div", {
                          className: "text-slate-300 mx-1 text-sm"
                        }, "/"), React.createElement(Link.make, {
                          children: "LaTeXのガイド",
                          to: "/latex/introduction",
                          className: "text-slate-700 text-sm"
                        }))));
}

var make = Header;

export {
  make ,
}
/* Link Not a pure module */
