// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Link from './Link.bs.js';
import * as React from 'react';
function Header(props) {
  return (
    <header>
      <div
        className={
          'container md:mx-auto max-w-4xl box-content ' +
          (props.isArticle ? 'xl:pr-72' : '') +
          ''
        }
      >
        <div className="p-4 flex justify-start items-center">
          <Link.make
            children={<h1 className="font-bold text-lg">gadgetlunatic</h1>}
            to="/"
          />
          <Link.make
            children="ブログ"
            to="/"
            className="text-slate-700 ml-4 text-sm"
          />
          <div className="text-slate-300 mx-1 text-sm">/</div>
          <Link.make
            children="LaTeXのガイド"
            to="/latex/introduction"
            className="text-slate-700 text-sm"
          />
        </div>
      </div>
    </header>
  );
}
var make = Header;
export { make };
/* Link Not a pure module */
