// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactHelmetAsync from "react-helmet-async";

function Head(props) {
  return React.createElement(ReactHelmetAsync.Helmet, {
              children: null
            }, React.createElement("title", undefined, props.title), React.createElement("link", {
                  href: "https://gadgetlunatic.com" + props.path + "",
                  rel: "canonical"
                }));
}

var make = Head;

export {
  make ,
}
/* react Not a pure module */
