// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
function Icon$Bar3(props) {
  return <svg className={props.className} fill="none" stroke="currentColor" strokeWidth="1.5" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" strokeLinecap="round" strokeLinejoin="round" /></svg>;
}
var Bar3 = {
  make: Icon$Bar3
};
function Icon$XMark(props) {
  return <svg className={props.className} fill="none" stroke="currentColor" strokeWidth="1.5" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M6 18L18 6M6 6l12 12" strokeLinecap="round" strokeLinejoin="round" /></svg>;
}
var XMark = {
  make: Icon$XMark
};
export { Bar3, XMark };
/* react Not a pure module */