// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Router from "../hooks/Router.bs.js";
var getHref = e => e.currentTarget.href || '';
var getOrigin = () => window.location.origin;
function Link(props) {
  var onClick = props.onClick;
  var handleClick = function (e) {
    var href = getHref(e);
    if (href.startsWith(Curry._1(getOrigin, undefined))) {
      e.preventDefault();
      Router.push(href);
    }
    if (onClick !== undefined) {
      return Curry._1(onClick, e);
    }
  };
  return <a className={props.className} href={props.to} onClick={handleClick}>{props.children}</a>;
}
var make = Link;
export { getHref, getOrigin, make };
/* react Not a pure module */