// Generated by ReScript, PLEASE EDIT WITH CARE

import { MouseEvent, ReactNode, useCallback } from 'react';
import { useNavigate } from '../utils/router';

export const Link = ({
  onClick,
  className,
  to,
  children,
}: {
  to: string;
  onClick?: (e: MouseEvent<HTMLAnchorElement>) => void;
  className?: string;
  children: ReactNode;
}) => {
  const navigate = useNavigate();

  const handleClick = useCallback((e: MouseEvent<HTMLAnchorElement>) => {
    const href = e.currentTarget.href || '';
    if (href.startsWith(window.location.origin)) {
      e.preventDefault();
      navigate(href);
    }
    onClick?.(e);
  }, []);

  return (
    <a className={className} href={to} onClick={handleClick}>
      {children}
    </a>
  );
};
