// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.bs.js";
import * as React from "react";
import * as Router from "./hooks/Router.bs.js";
import * as Client from "react-dom/client";
import * as ReactHelmetAsync from "react-helmet-async";
var container = document.querySelector("#root");
if (!(container == null)) {
  Client.hydrateRoot(container, <React.StrictMode children={<ReactHelmetAsync.HelmetProvider children={<Router.Provider.make children={<App.make />} />} context={undefined} />} />);
}
export {};
/* container Not a pure module */