// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from './App.bs.js';
import * as React from 'react';
import * as Router from './hooks/Router.bs.js';
import * as ReactHelmetAsync from 'react-helmet-async';
function EntryServer(props) {
  return (
    <React.StrictMode
      children={
        <ReactHelmetAsync.HelmetProvider
          children={
            <Router.Provider.make
              children={<App.make />}
              serverUrlString={props.serverUrlString}
            />
          }
          context={props.context}
        />
      }
    />
  );
}
var make = EntryServer;
export { make };
/* App Not a pure module */
